const fs=require('fs'),assert=require('node:assert/strict');
const {PGlite}=require('../.production-test-runtime/node_modules/@electric-sql/pglite');
(async()=>{
const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
insert into auth.users values('11111111-1111-1111-1111-111111111111','staff@test',now());
create function auth.uid() returns uuid language sql as $$select '11111111-1111-1111-1111-111111111111'::uuid$$;
create function cc_production_role() returns text language sql as $$select 'admin'::text$$;
create table customers(email text,is_employee bool);create table store_menu(name text);insert into store_menu values('Coffee');
create table store_orders(id uuid primary key default gen_random_uuid(),customer_phone text,status text,payment_status text);`);
for(const file of ['20260921d_loyalty_cards.sql','20260921f_loyalty_kitchen_lookup.sql','20260922_group_loyalty.sql','20260922b_auto_loyalty_cards.sql','20260922b_auto_loyalty_cards.sql']) await db.exec(fs.readFileSync('migrations/'+file,'utf8'));
await db.exec(`insert into store_orders(customer_phone,status,payment_status,customer_group_phones) values('9876543210','pending','pending','["9123443210","9876543210"]')`);
let rows=(await db.query('select * from cc_loyalty_members order by phone')).rows;assert.equal(rows.length,2);assert.equal(new Set(rows.map(r=>r.card_code)).size,2);assert.ok(rows.every(r=>r.name_pending && r.stamp_count===0 && r.schedule.length===0));
await db.exec(`update store_orders set status='collected',payment_status='paid'`);
assert.ok((await db.query('select stamp_count from cc_loyalty_members')).rows.every(r=>r.stamp_count===1));
let id=rows[0].id;
await db.query(`select cc_loyalty_profile('save',$1::jsonb)`,[JSON.stringify({member_id:id,name:'Friend',schedule:[{day:10,item:'Coffee'}]})]);
let saved=(await db.query('select * from cc_loyalty_members where id=$1',[id])).rows[0];assert.equal(saved.name,'Friend');assert.equal(saved.name_pending,false);assert.equal(saved.stamp_count,1);
await assert.rejects(db.query(`select cc_loyalty_profile('save',$1::jsonb)`,[JSON.stringify({member_id:id,name:' '})]),/Enter a name/);
await db.exec(`create or replace function cc_production_role() returns text language sql as $$select 'sales'::text$$;`);
await db.query(`select cc_loyalty_profile('save',$1::jsonb)`,[JSON.stringify({member_id:id,name:'Friend updated'})]);
await assert.rejects(db.query(`select cc_loyalty_profile('save',$1::jsonb)`,[JSON.stringify({member_id:rows[1].id,name:'Friend',schedule:[{day:10,item:'Coffee'}]})]),/Only admin/);
await db.exec(`create or replace function cc_production_role() returns text language sql as $$select 'customer'::text$$;`);
await assert.rejects(db.query(`select cc_loyalty_profile('ensure_orders','{"ids":[]}'::jsonb)`),/Staff access/);
await db.exec(`insert into store_orders(customer_phone,status,payment_status) values('9999999999','pending','pending')`);
assert.equal((await db.query('select count(*)::int n from cc_loyalty_members')).rows[0].n,2);
await db.exec(`create or replace function cc_production_role() returns text language sql as $$select 'sales'::text$$;`);
let order=(await db.query("select id from store_orders where customer_phone='9999999999'")).rows[0];
await db.query(`select cc_loyalty_profile('ensure_orders',$1::jsonb)`,[JSON.stringify({ids:[order.id]})]);
await db.query(`select cc_loyalty_profile('ensure_orders',$1::jsonb)`,[JSON.stringify({ids:[order.id]})]);
assert.equal((await db.query('select count(*)::int n from cc_loyalty_members')).rows[0].n,3);
await db.close();console.log('PASS auto cards: full migrations/rerun, duplicate phones, code collisions, pending names, stamp preservation, admin rewards, staff rename, customer denial, existing open-order enrolment.');
})().catch(e=>{console.error(e);process.exit(1);});
