const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const {PGlite}=require('../.production-test-runtime/node_modules/@electric-sql/pglite');
(async()=>{
 const ctx={window:{},document:{readyState:'loading',addEventListener(){}},console};vm.createContext(ctx);vm.runInContext(fs.readFileSync('loyalty-cards.js','utf8'),ctx);
 assert.equal(JSON.stringify(ctx.lcParseGroupPhones('9876543210, +91 9876543210, 9123456780')),JSON.stringify(['+919876543210','+919123456780']));
 assert.throws(()=>ctx.lcParseGroupPhones('123'));assert.throws(()=>ctx.lcParseGroupPhones('abcd9876543210'));
 assert.equal(ctx.lcOrderPhones({customer_phone:'9876543210',customer_group_phones:['+919876543210','+919123456780']}).length,2);
 let calls=0;ctx.lcCommand=async(action,payload)=>{calls++;assert.equal(action,'lookup_many');assert.equal(payload.phones.length,2);return {members:[{phone:'+919123456780',name:'Friend'}]};};
 assert.equal((await ctx.lcLoyaltyMapFor([{customer_phone:'9876543210',customer_group_phones:['+919123456780']}]))['9123456780'].name,'Friend');assert.equal(calls,1);
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create schema auth;
 create function auth.uid() returns uuid language sql as $$select '11111111-1111-1111-1111-111111111111'::uuid$$;
 create function public.cc_loyalty_role() returns text language sql as $$select 'staff'::text$$;
 create table cc_loyalty_members(id uuid primary key default gen_random_uuid(),phone text unique,stamp_count int default 0,suspended bool default false,updated_at timestamptz);
 create table cc_loyalty_stamp_log(member_id uuid,from_count int,to_count int,staff_name text,actor uuid,created_at timestamptz default now());
 create table store_orders(id int primary key,customer_phone text,status text,payment_status text);
 insert into cc_loyalty_members(phone) values('+919876543210'),('+919123456780');`);
 const sql=fs.readFileSync('migrations/20260922_group_loyalty.sql','utf8');await db.exec(sql);await db.exec(sql);
 await db.exec(`insert into store_orders values(1,'9876543210','pending','pending','["9123456780","+919123456780"]');`);
 assert.equal((await db.query('select customer_group_phones from store_orders')).rows[0].customer_group_phones.length,1);
 assert.equal((await db.query('select sum(stamp_count)::int n from cc_loyalty_members')).rows[0].n,0);
 await db.exec(`update store_orders set status='collected',payment_status='paid' where id=1;`);
 assert.equal((await db.query('select sum(stamp_count)::int n from cc_loyalty_members')).rows[0].n,2);
 await db.exec(`insert into store_orders values(2,'9876543210','collected','paid','["9123456780"]');update store_orders set status='collected' where id=1;`);
 assert.equal((await db.query('select count(*)::int n from cc_loyalty_stamp_log')).rows[0].n,2);
 await assert.rejects(db.exec(`update store_orders set customer_group_phones='[]' where id=1`),/closed/);
 await assert.rejects(db.exec(`insert into store_orders values(3,null,'pending','pending','["12"]')`),/10 digits/);
 await db.exec(`create or replace function cc_loyalty_role() returns text language sql as $$select 'customer'::text$$;`);
 await assert.rejects(db.exec(`insert into store_orders values(4,null,'pending','pending','["9123456780"]')`),/Only staff/);
 await db.close();console.log('PASS group phones: normalize/dedupe, validation, one batched lookup; SQL rerun, no early stamps, group collection, daily dedupe, closed edits and customer rejection.');
})().catch(e=>{console.error(e);process.exit(1);});
