const fs=require('fs'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {PGlite}=require('../.production-test-runtime/node_modules/@electric-sql/pglite');
(async()=>{
 const db=new PGlite(),admin=randomUUID(),staff=randomUUID(),alice=randomUUID(),bob=randomUUID();
 await db.exec(`create role anon;create role authenticated;create schema auth;
 create table auth.users(id uuid primary key,email text,phone text,phone_confirmed_at timestamptz,email_confirmed_at timestamptz);
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table customers(email text,is_employee boolean);
 create function cc_production_role() returns text language sql as $$ select case when auth.uid()='${admin}'::uuid then 'admin' end $$;
 create table store_menu(name text);
 insert into store_menu values('Coffee'),('Brownie');
 create table store_orders(id uuid primary key default gen_random_uuid(),customer_id uuid,items jsonb,total numeric,status text default 'pending',payment_status text default 'pending');
 insert into auth.users values('${admin}','admin@test','911111111111',now(),now()),('${staff}','staff@test','912222222222',now(),now()),('${alice}','alice@test','913333333333',now(),now()),('${bob}','bob@test','914444444444',now(),now());
 insert into customers values('staff@test',true);`);
 const sql=fs.readFileSync('migrations/20260921_premium_cards.sql','utf8');await db.exec(sql);await db.exec(sql);const emailPatch=fs.readFileSync('migrations/20260921b_premium_email_verification.sql','utf8');await db.exec(emailPatch);await db.exec(emailPatch);
 const actor=id=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
 const command=async(a,p={})=>(await db.query('select cc_premium_command($1,$2::jsonb) x',[a,JSON.stringify(p)])).rows[0].x;
 const scalar=async(q,p=[])=>(Object.values((await db.query(q,p)).rows[0])[0]);
 const item=(qty=3)=>[{name:'Coffee',qty,price:30}];
 async function order(owner,items=item(),total=90){return scalar('insert into store_orders(customer_id,items,total) values($1,$2,$3) returning id',[owner,JSON.stringify(items),total]);}
 async function collect(id){await db.query("update store_orders set status='collected',payment_status='paid' where id=$1",[id]);}
 await actor(alice);await assert.rejects(()=>command('issue',{}),/Admin/);
 await actor(admin);
 const ca=await command('issue',{name:'Alice',email:'alice@test',minimum_spend:0,schedule:[{day:1,item:'Coffee'},{day:100,item:'Brownie'}]});
 const cb=await command('issue',{name:'Bob',email:'bob@test',phone:'+914444444444',minimum_spend:0,schedule:[{day:1,item:'Coffee'}]});
 await assert.rejects(()=>command('issue',{name:'Again',email:'alice@test',schedule:[{day:1,item:'Coffee'}]}),/duplicate/);
 await db.query('update auth.users set phone=null,phone_confirmed_at=null where id in ($1,$2)',[alice,bob]);
 await db.exec(emailPatch);assert.equal(await scalar('select number from cc_premium_cards where id=$1',[ca.id]),ca.number,'email upgrade preserves issued cards');
 await actor(alice);const first=await order(alice);assert.equal(Number(await scalar('select count(*) from cc_premium_allocations where order_id=$1',[first])),1);
 await assert.rejects(()=>collect(first),/Staff must/);await actor(staff);await collect(first);
 assert.equal(Number(await scalar('select count(*) from cc_premium_stamps')),1);
 await collect(first);assert.equal(Number(await scalar('select count(*) from cc_premium_stamps')),1);
 await actor(alice);const second=await order(alice);await actor(staff);await collect(second);assert.equal(Number(await scalar('select count(*) from cc_premium_stamps')),1);
 await db.query("update store_orders set status='cancelled' where id=$1",[first]);assert.equal(Number(await scalar('select count(*) from cc_premium_stamps')),1,'other purchase preserves stamp');
 const group=await order(null);await actor(bob);const code=await command('code');await actor(staff);await command('assign',{order_id:group,code:code.code,items:[{index:0,quantity:1}]});
 await assert.rejects(()=>command('assign',{order_id:group,code:code.code,items:[{index:0,quantity:1}]}),/expired|used/);
 await actor(alice);const acode=await command('code');await actor(staff);
 await assert.rejects(()=>command('assign',{order_id:group,code:acode.code,items:[{index:0,quantity:3}]}),/already belong/);
 await command('assign',{order_id:group,code:acode.code,items:[{index:0,quantity:2}]});
 await collect(group);assert.equal(Number(await scalar('select count(*) from cc_premium_stamps')),2);
 assert.equal(Number(await scalar('select amount from cc_premium_purchases where order_id=$1 and member_id=$2',[group,cb.member_id])),30);
 await assert.rejects(()=>db.query('update store_orders set total=10 where id=$1',[group]),/cannot be edited/);
 const reward=await scalar('select id from cc_premium_rewards where member_id=$1',[cb.member_id]);
 await db.exec("update cc_premium_codes set created_at=now()-interval '1 minute'");
 await actor(bob);const rcode=await command('code',{reward_id:reward});await actor(staff);const ro=await order(null,[],0);
 await command('reserve',{order_id:ro,code:rcode.code});assert.equal(await scalar('select status from cc_premium_rewards where id=$1',[reward]),'reserved');
 await collect(ro);assert.equal(await scalar('select status from cc_premium_rewards where id=$1',[reward]),'redeemed');assert.equal(Number(await scalar('select count(*) from cc_premium_stamps')),2,'complimentary redemption adds no stamp');
 await db.query("update store_orders set status='cancelled' where id=$1",[group]);assert.equal(await scalar('select status from cc_premium_rewards where id=$1',[reward]),'review');
 assert.equal(Number(await scalar('select count(*) from cc_premium_reviews')),1);
 const reviewId=await scalar('select id from cc_premium_reviews limit 1');
 await actor(staff);await assert.rejects(()=>command('review',{id:reviewId,approve:true,note:'Keep reward',resolution:'honor_reward'}),/Admin/);
 await actor(admin);await command('review',{id:reviewId,approve:true,note:'Honor already delivered coffee',resolution:'honor_reward'});
 assert.equal(await scalar('select status from cc_premium_rewards where id=$1',[reward]),'redeemed');
 const correction=await command('request_review',{member_id:ca.member_id,order_id:second,reason:'Exclude test purchase'});
 await command('review',{id:correction.id,approve:true,note:'Reviewed purchase evidence',resolution:'exclude_purchase'});
 assert.equal(Number(await scalar('select count(*) from cc_premium_stamps where member_id=$1',[ca.member_id])),0);
 const restore=await command('request_review',{member_id:ca.member_id,order_id:second,reason:'Restore test purchase'});
 await command('review',{id:restore.id,approve:true,note:'Purchase was paid and collected',resolution:'restore_purchase'});
 assert.equal(Number(await scalar('select count(*) from cc_premium_stamps where member_id=$1',[ca.member_id])),1);
 const charlie=randomUUID();await db.query('insert into auth.users values($1,$2,$3,null,null)',[charlie,'charlie@test','915555555555']);
 await assert.rejects(()=>command('issue',{name:'Charlie',email:'charlie@test',phone:'+915555555555',minimum_spend:60,schedule:[{day:15,item:'Brownie'}]}),/verify/);
 await db.query('update auth.users set email_confirmed_at=now(),phone=null where id=$1',[charlie]);
 const cc=await command('issue',{name:'Charlie',email:'charlie@test',phone:'+915555555555',minimum_spend:60,schedule:[{day:15,item:'Brownie'}]});
 await actor(charlie);const c1=await order(charlie,item(1),30);await actor(staff);await collect(c1);
 assert.equal(Number(await scalar('select count(*) from cc_premium_stamps where member_id=$1',[cc.member_id])),0);
 await actor(charlie);const c2=await order(charlie,item(1),30);await actor(staff);await collect(c2);
 assert.equal(Number(await scalar('select count(*) from cc_premium_stamps where member_id=$1',[cc.member_id])),1,'minimum spend sums assigned paid purchases per day');
 await actor(charlie);const expired=await command('code');await db.query("update cc_premium_codes set expires_at=now()-interval '1 second' where token=$1",[expired.code]);
 await actor(staff);const c3=await order(null);await assert.rejects(()=>command('assign',{order_id:c3,code:expired.code,items:[{index:0,quantity:1}]}),/expired/);
 await actor(alice);await db.exec('set role authenticated');await assert.rejects(()=>db.query('select * from cc_premium_members'),/permission denied/);
 const view=await scalar('select cc_premium_view()');assert.equal(view.member.name,'Alice');assert.equal(view.members,undefined);
 await assert.rejects(()=>command('suspend',{member_id:ca.member_id,suspended:true,reason:'test'}),/Admin/);await db.exec('reset role');
 // Fill a complete cycle with dated evidence, then a new date renews exactly once.
 await db.query('delete from cc_premium_stamps where member_id=$1',[ca.member_id]);
 await db.query("insert into cc_premium_stamps(member_id,card_id,business_day) select $1,$2,current_date-101+i from generate_series(1,100) i",[ca.member_id,ca.id]);
 await db.query("insert into cc_premium_purchases(order_id,member_id,business_day,amount) values($1,$2,current_date,30) on conflict(order_id,member_id) do update set business_day=current_date,reversed=false",[first,ca.member_id]);
 await db.query('select cc_premium_reconcile($1,current_date)',[ca.member_id]);await db.query('select cc_premium_reconcile($1,current_date)',[ca.member_id]);
 assert.equal(Number(await scalar('select max(cycle) from cc_premium_cards where member_id=$1',[ca.member_id])),2);assert.equal(Number(await scalar('select count(*) from cc_premium_stamps where member_id=$1 and business_day=current_date',[ca.member_id])),1);
 await db.close();console.log('PASS premium database: reruns, authorization, own orders, daily dedupe, shared quantities, one-use codes, redemption, reversals, privacy and 100-day renewal.');
})().catch(e=>{console.error(e);process.exit(1);});
